print('Организация программ и методы строк')
my_string = input('Введите Вашу строку: ')
print((len(my_string)), 'знаков и символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])